version: 1.0
configuration:
  backupPath: \\scb.intra\users\H\SCBHARK\Mina Dokument\Backuper
  shellConfiguration:
    pathToOneNote: C:\Program Files\Microsoft Office\root\Office16\ONENOTE
    browser: C:\Program Files (x86)\Microsoft\Edge\Application\msedge
    displaySeparator: \t
    autostart: false
  showDiagnosticInformation: false
  defaultCommand: find
  codeEditor: C:\Users\harri\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022    
  metadata:
    name: Test
    description: En exempelbeskrivning
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 173831af7e77b8bd33e32fce0b4e646d
    name: Serialog
  components:
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 30cc55b7c6f29f951be3df97f634fb71
    name: PainKiller Core
  - component: PainKiller.PowerCommands.KnowledgeDBCommands.dll
    checksum: c8d128cde99a5ee06b56e8337c10b1e2
    name: My Example Command
  secret:
    secrets:
    - name: localDB
      options:
        target: User
  environment:
    variables:
    - name: KEY_VAULT_NAME
      environmentVariableTarget: User
    - name: AZURE_CLIENT_ID
      environmentVariableTarget: User 