version: 1.0
configuration:
  showDiagnosticInformation: false
  defaultCommand: commands
  codeEditor: C:\Users\%USERNAME%\AppData\Local\Programs\Microsoft VS Code\Code.exe
  repository: https://github.com/PowerCommands/PowerCommands2022
  backupPath: ..\..\..\..\Core\PainKiller.PowerCommands.Core\  
  defaultGitRepositoryPath: ..\..\..\..\..\
  commandDesignOverrides:
  - name: demo
    description: "Demo command just to try out how you could use the input, do not forget the MANDATORY option, will trigger a validation error otherwise! ;-)\n That is because the option name is typed with UPPERCASE letters, useful when you want a mandatory option\n The pause option on the other hand starts with a ! symbol meaning that if you add the --pause option you must also give it a value, an integer in this case."
    arguments: ""
    quotes: ""    
    options: "MANDATORY|!pause"
    examples: "//Must provide the MANDATORY option, will trigger a validation error otherwise|demo MANDATORY|//Test the pause service|demo --pause 5 MANDATORY"
    suggestions: ""
    useAsync: false
    showElapsedTime: true
  startupToolbar:
    hideToolbarOption: OnCommandHighlighted
    toolbarItems:
    - label: "[Type ->]"
      color: "Cyan"
    - label: "demo"
      color: "DarkGreen"
  metadata:
    name: $ext_projectname$
    description: Description of my project
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 13b9944b55efe60362720a679f17a22c
    name: Serialog
  components:  
  - component: $ext_projectname$Commands.dll
    checksum: a2df61ea89e4f9ec265d921bfad87193
    name: $ext_projectname$
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 4f04313db8e67b2bc4b059c478a900af
    name: PainKiller Core
  bookmark:
    bookmarks:
    - name: Program
      path: C:\Program Files
      index: 0
  secret:
    secrets:    
  environment:
    variables:
    - name: OS
      environmentVariableTarget: Machine