version: 1.0
configuration:
  defaultGitRepositoryPath: C:\repos\PowerCommands2022
  projectsRelativePath: Projects
  comparisonProjects:
  - name: demo
  regressionProjects:
  - name: reg
  showDiagnosticInformation: false
  codeEditor: C:\Users\harri\AppData\Local\Programs\Microsoft VS Code\Code.exe
  metadata:
    name: Test
    description: En exempelbeskrivning
  log:
    fileName: powercommands.log
    filePath: logs
    rollingIntervall: Day
    restrictedToMinimumLevel: Information
    component: PainKiller.SerilogExtensions.dll
    checksum: 173831af7e77b8bd33e32fce0b4e646d
    name: Serialog
  components:
  - component: PainKiller.PowerCommands.Core.dll
    checksum: 30cc55b7c6f29f951be3df97f634fb71
    name: PainKiller Core
  - component: PainKiller.PowerCommands.GlitchFinderCommands.dll
    checksum: dc2e52e31c54601b3fa057b9ec3724e6
    name: Glithfinder commands
  secret:
    secrets:
    - name: localDB
      options:
        target: User
